/* Generated from master/pokemonTable_HatchMon_Canonical_v2.xlsx. Do not hand-edit.
 * Playable roster: species connected by an evolution rule with MinAgeDays informed.
 * Keys are save-visible legacy IDs pinned in master/legacyIds.json.
 */
const evolutionTable = {
  pichu: {canonicalId: "0172A0", nombre: "Pichu"},
  pikachu: {canonicalId: "0025A0", nombre: "Pikachu"},
  raichu: {canonicalId: "0026A0", nombre: "Raichu"},
  raichualola: {canonicalId: "0026L0", nombre: "Raichu (Alolan Form)"},
  eevee: {canonicalId: "0133A0", nombre: "Eevee"},
  vaporeon: {canonicalId: "0134A0", nombre: "Vaporeon"},
  jolteon: {canonicalId: "0135A0", nombre: "Jolteon"},
  flareon: {canonicalId: "0136A0", nombre: "Flareon"},
  espeon: {canonicalId: "0196A0", nombre: "Espeon"},
  umbreon: {canonicalId: "0197A0", nombre: "Umbreon"},
  leafeon: {canonicalId: "0470A0", nombre: "Leafeon"},
  glaceon: {canonicalId: "0471A0", nombre: "Glaceon"},
  sylveon: {canonicalId: "0700A0", nombre: "Sylveon"},
  tyrogue: {canonicalId: "0236A0", nombre: "Tyrogue"},
  hitmonlee: {canonicalId: "0106A0", nombre: "Hitmonlee"},
  hitmonchan: {canonicalId: "0107A0", nombre: "Hitmonchan"},
  hitmontop: {canonicalId: "0237A0", nombre: "Hitmontop"},
  munchlax: {canonicalId: "0446A0", nombre: "Munchlax"},
  snorlax: {canonicalId: "0143A0", nombre: "Snorlax"},
  riolu: {canonicalId: "0447A0", nombre: "Riolu"},
  lucario: {canonicalId: "0448A0", nombre: "Lucario"},
  toxel: {canonicalId: "0848A0", nombre: "Toxel"},
  toxtricityamp: {canonicalId: "0849A0", nombre: "Toxtricity (Amped Form)"},
  toxtricitylow: {canonicalId: "0849B0", nombre: "Toxtricity (Low Key Form)"},
  cleffa: {canonicalId: "0173A0", nombre: "Cleffa"},
  clefairy: {canonicalId: "0035A0", nombre: "Clefairy"},
  clefable: {canonicalId: "0036A0", nombre: "Clefable"},
  igglybuff: {canonicalId: "0174A0", nombre: "Igglybuff"},
  jigglypuff: {canonicalId: "0039A0", nombre: "Jigglypuff"},
  wigglytuff: {canonicalId: "0040A0", nombre: "Wigglytuff"},
  togepi: {canonicalId: "0175A0", nombre: "Togepi"},
  togetic: {canonicalId: "0176A0", nombre: "Togetic"},
  togekiss: {canonicalId: "0468A0", nombre: "Togekiss"},
  azurill: {canonicalId: "0298A0", nombre: "Azurill"},
  marill: {canonicalId: "0183A0", nombre: "Marill"},
  azumarill: {canonicalId: "0184A0", nombre: "Azumarill"},
  mantyke: {canonicalId: "0458A0", nombre: "Mantyke"},
  mantine: {canonicalId: "0226A0", nombre: "Mantine"},
  elekid: {canonicalId: "0239A0", nombre: "Elekid"},
  electabuzz: {canonicalId: "0125A0", nombre: "Electabuzz"},
  electivire: {canonicalId: "0466A0", nombre: "Electivire"},
  magby: {canonicalId: "0240A0", nombre: "Magby"},
  magmar: {canonicalId: "0126A0", nombre: "Magmar"},
  magmortar: {canonicalId: "0467A0", nombre: "Magmortar"},
  bulbasaur: {canonicalId: "0001A0", nombre: "Bulbasaur"},
  ivysaur: {canonicalId: "0002A0", nombre: "Ivysaur"},
  venusaur: {canonicalId: "0003A0", nombre: "Venusaur"},
  charmander: {canonicalId: "0004A0", nombre: "Charmander"},
  charmeleon: {canonicalId: "0005A0", nombre: "Charmeleon"},
  charizard: {canonicalId: "0006A0", nombre: "Charizard"},
  squirtle: {canonicalId: "0007A0", nombre: "Squirtle"},
  wartortle: {canonicalId: "0008A0", nombre: "Wartortle"},
  blastoise: {canonicalId: "0009A0", nombre: "Blastoise"},
  dratini: {canonicalId: "0147A0", nombre: "Dratini"},
  dragonair: {canonicalId: "0148A0", nombre: "Dragonair"},
  dragonite: {canonicalId: "0149A0", nombre: "Dragonite"},
  abra: {canonicalId: "0063A0", nombre: "Abra"},
  kadabra: {canonicalId: "0064A0", nombre: "Kadabra"},
  alakazam: {canonicalId: "0065A0", nombre: "Alakazam"},
  growlithe: {canonicalId: "0058A0", nombre: "Growlithe"},
  arcanine: {canonicalId: "0059A0", nombre: "Arcanine"},
  chingling: {canonicalId: "0433A0", nombre: "Chingling"},
  chimecho: {canonicalId: "0358A0", nombre: "Chimecho"},
  budew: {canonicalId: "0406A0", nombre: "Budew"},
  roselia: {canonicalId: "0315A0", nombre: "Roselia"},
  roserade: {canonicalId: "0407A0", nombre: "Roserade"},
  wynaut: {canonicalId: "0360A0", nombre: "Wynaut"},
  wobbuffet: {canonicalId: "0202A0", nombre: "Wobbuffet"},
  bonsly: {canonicalId: "0438A0", nombre: "Bonsly"},
  sudowoodo: {canonicalId: "0185A0", nombre: "Sudowoodo"},
  mimejr: {canonicalId: "0439A0", nombre: "Mime Jr."},
  mrmime: {canonicalId: "0122A0", nombre: "Mr. Mime"},
  happiny: {canonicalId: "0440A0", nombre: "Happiny"},
  chansey: {canonicalId: "0113A0", nombre: "Chansey"},
  blissey: {canonicalId: "0242A0", nombre: "Blissey"},
  jynx: {canonicalId: "0124A0", nombre: "Jynx"},
  smoochum: {canonicalId: "0238A0", nombre: "Smoochum"},
  caterpie: {canonicalId: "0010A0", nombre: "Caterpie"},
  metapod: {canonicalId: "0011A0", nombre: "Metapod"},
  butterfree: {canonicalId: "0012A0", nombre: "Butterfree"},
  pidgey: {canonicalId: "0016A0", nombre: "Pidgey"},
  pidgeotto: {canonicalId: "0017A0", nombre: "Pidgeotto"},
  pidgeot: {canonicalId: "0018A0", nombre: "Pidgeot"},
  rattata: {canonicalId: "0019A0", nombre: "Rattata"},
  rattataalolanform: {canonicalId: "0019L0", nombre: "Rattata (Alolan Form)"},
  raticate: {canonicalId: "0020A0", nombre: "Raticate"},
  raticatealolanform: {canonicalId: "0020L0", nombre: "Raticate (Alolan Form)"},
  vulpix: {canonicalId: "0037A0", nombre: "Vulpix"},
  vulpixalolanform: {canonicalId: "0037L0", nombre: "Vulpix (Alolan Form)"},
  ninetales: {canonicalId: "0038A0", nombre: "Ninetales"},
  ninetalesalolanform: {canonicalId: "0038L0", nombre: "Ninetales (Alolan Form)"},
  chikorita: {canonicalId: "0152A0", nombre: "Chikorita"},
  bayleef: {canonicalId: "0153A0", nombre: "Bayleef"},
  meganium: {canonicalId: "0154A0", nombre: "Meganium"},
  treecko: {canonicalId: "0252A0", nombre: "Treecko"},
  grovyle: {canonicalId: "0253A0", nombre: "Grovyle"},
  sceptile: {canonicalId: "0254A0", nombre: "Sceptile"},
  ralts: {canonicalId: "0280A0", nombre: "Ralts"},
  kirlia: {canonicalId: "0281A0", nombre: "Kirlia"},
  gardevoir: {canonicalId: "0282A0", nombre: "Gardevoir"},
  aron: {canonicalId: "0304A0", nombre: "Aron"},
  lairon: {canonicalId: "0305A0", nombre: "Lairon"},
  aggron: {canonicalId: "0306A0", nombre: "Aggron"},
  piplup: {canonicalId: "0393A0", nombre: "Piplup"},
  prinplup: {canonicalId: "0394A0", nombre: "Prinplup"},
  empoleon: {canonicalId: "0395A0", nombre: "Empoleon"},
  gallade: {canonicalId: "0475A0", nombre: "Gallade"},
  tinkatink: {canonicalId: "0957A0", nombre: "Tinkatink"},
  tinkatuff: {canonicalId: "0958A0", nombre: "Tinkatuff"},
  tinkaton: {canonicalId: "0959A0", nombre: "Tinkaton"},
  lapras: {canonicalId: "0131A0", nombre: "Lapras"},
  mew: {canonicalId: "0151A0", nombre: "Mew"},
};
