const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const ctx=vm.createContext({HatchEnvironment:{isDevelopmentEnvironment:()=>true},TextEncoder,TextDecoder,btoa,atob,crypto:require('node:crypto').webcrypto});const run=s=>vm.runInContext(s,ctx);
run(fs.readFileSync('i18n.js','utf8'));
for(const f of ['evolutionTable.js','hatchmonData_v2.js','pokemonDataAdapter.js','vitalSimulation.js','relationship.js','pokedex.js','shiny.js','assets/skins/themes.js','shellSkins.js','styleTracing.js','trainingActivities.js','socialEngine.js'])run(fs.readFileSync(f,'utf8'));
run(fs.readFileSync('index.html','utf8').match(/<script type="text\/plain" id="game-source">([\s\S]*?)<\/script>/)[1].split('// UI:')[0]);
function born(id='magby'){run(`state=freshState();state.incubationRemaining=0;hatch(()=>0);finishBirthScene();setNickname('Brasa');state.pokemonId='${id}';state.gender=PokemonData.gender(state.pokemonId);state.age=10*HOUR;state.stageAge=state.age;state.care={hambre:75,felicidad:21,energia:61,higiene:88};state.training={iq:12,strength:23,kindness:34,style:8};state.vital.dirt=32;state.vital.poops=[{id:1,createdAge:0}];state.vital.poopSerial=1;state.pokerus=true;state.vital.illnessCause='food';`)}
function snapshot(){run('var before=HatchMonSocial.copy(state)')}
function preserved(){for(const k of ['care','vital','pokerus','social','nickname','gender','inventory','consumed','trainer','lightsOff'])assert.equal(run(`JSON.stringify(state.${k})===JSON.stringify(before.${k})`),true,k);assert.equal(run('validSave(state)'),true)}
born();snapshot();assert.equal(run('forceEvolution("magmar")'),true);preserved();assert.equal(run('state.age/HOUR'),24);assert.equal(run('state.training.style'),50);for(const k of ['iq','strength','kindness'])assert.equal(run(`state.training.${k}===before.training.${k}`),true);assert.ok(run('state.relationship.points>=PokemonData.rules("magby")[0].MinBond'));assert.equal(run('Vital.getLifeStage(state)'),'JOVEN');
console.log('Real example Magby 10h/Style8 -> Magmar 24h/Style50, happiness70 for6h synthetic evidence; care75/21/61/88 unchanged; lifespan',run('state.vital.lifespan/HOUR'),'hours, LifeStage',run('Vital.getLifeStage(state)'));
// All real outgoing rules, including branches, item routes, actions and sustained evidence.
const routes=run('Object.entries(evolutionConfig).flatMap(([from,p])=>p.rules.filter(r=>r.enabled!==false).map(r=>({from,to:r.to})))');
for(const {from,to} of routes){born(from);snapshot();assert.equal(run(`forceEvolution('${to}')`),true,`${from}>${to}`);preserved();assert.equal(run('state.pokemonId'),to);assert.equal(run('state.milestones.at(-1).testing'),true);assert.equal(run('state.milestones.at(-1).item'),null)}
born('tyrogue');run('state.age=80*HOUR;state.stageAge=state.age;state.training.strength=95');snapshot();run('forceEvolution("hitmonlee")');preserved();assert.equal(run('state.age/HOUR'),80);assert.equal(run('state.training.strength'),95);assert.equal(run('state.training.style'),30);assert.equal(run('Vital.getLifeStage(state)'),'SENIOR');
born('marill');run('state.actions.jugar=2');run('forceEvolution("azumarill")');assert.equal(run('state.milestones.at(-1).actions.jugar'),10);
born('marill');run('state.actions.jugar=20');run('forceEvolution("azumarill")');assert.equal(run('state.milestones.at(-1).actions.jugar'),20);
born('eevee');snapshot();assert.equal(run('forceEvolution("magmar")'),false);assert.equal(run('JSON.stringify(state)===JSON.stringify(before)'),true);
// Normal evolution still requires actual care and an inventory item; testing evidence is ephemeral.
born('pichu');run('state.age=DAY;state.sustained["felicidad:70"]=6*HOUR');assert.equal(run('conditionsMet(current().rules[0])'),false);run('state.care.felicidad=70;state.relationship.points=Relationship.evaluateMinBond(state,PokemonData.rules("pichu")[0].MinBond).minimumPoints');assert.equal(run('evolve(current().rules[0])'),true);
born('pikachu');run('state.age=2*DAY');assert.equal(run('evolve(current().rules[0],"thunder")'),false);run('state.inventory.thunder=1');assert.equal(run('evolve(current().rules[0],"thunder")'),true);assert.equal(run('state.inventory.thunder'),0);
// No live bank; profiles remain valid for breeding, never importable as companions.
born();run('state.pokerus=false;var profile=exportEntity()');born();assert.throws(()=>run('importEntity(profile)'),/Solo se importan huevos/);assert.equal(run('typeof activateEntity'),'undefined');assert.equal(run('Object.hasOwn(state.social,"collection")'),false);
run('var eggState=freshState();var egg={...eggState.social.active,kind:"egg",speciesId:null,snapshot:snapshotOf(eggState)};var eggCode=HatchMonSocial.pack(egg);importEntity(eggCode);var stored=JSON.stringify(state.social.eggs)');assert.equal(run('state.social.eggs.length'),1);assert.throws(()=>run('incubateStoredEgg(egg.id)'),/compañero vivo/);run('advanceGameTime(3*HOUR)');assert.equal(run('JSON.stringify(state.social.eggs)===stored'),true);
run('die("neglect");var deadId=state.social.active.id');assert.equal(run('state.social.memorials.length'),1);assert.equal(run('state.social.memorials[0].snapshot.vital.deathCause'),'neglect');assert.equal(run('validSave(state)'),true);assert.throws(()=>run('incubateStoredEgg(deadId)'),/Solo puedes/);run('rememberDeath()');assert.equal(run('state.social.memorials.length'),1);
run('incubateStoredEgg(egg.id)');assert.equal(run('state.phase'),'egg');assert.equal(run('state.vital'),null);assert.equal(run('state.age'),0);assert.equal(run('state.social.eggs.length'),0);assert.equal(run('state.social.memorials.length'),1);assert.equal(run('validSave(state)'),true);
run('var bad=HatchMonSocial.copy(state);bad.version=10');assert.equal(run('validSave(bad)'),false);assert.equal(run('typeof migrateSave'),'function');
// Persisted bank cannot contain a living or dead snapshot; stored egg remains inert.
run('var bad=HatchMonSocial.copy(state);bad.social.eggs.push(bad.social.memorials[0])');assert.equal(run('validSave(bad)'),false);
console.log('PASS C.2: canonical preparation, care/physiology preservation, branches, actions, sustained, items, LifeStage independent, single living companion, inert eggs, permanent memories, schema11.');
