const assert=require('node:assert/strict'),fs=require('fs');const {setup}=require('./uiHarness.cjs');
(async()=>{
 const t=await setup();const {run,els,flush,advance,doc}=t;
 const initial=run('state.incubationRemaining');els['creature-button'].fire('click');assert.ok(run('state.incubationRemaining')<initial);assert.equal(els.toast.hidden,false);assert.equal(els['creature-button'].classList.contains('heat-reaction'),true);assert.equal(els['egg-hint'].hidden,false);
 run('state.incubationRemaining=0;hatch(()=>0);render()');await flush();advance(16*1000/5.5+250+550);run('setNickname("");render()');await flush();
 assert.equal(els.sprite.dataset.visual,'asset');assert.equal(els.sprite.children[0].tagName,'canvas');assert.equal(els.sprite.textContent,'');
 run('showToast("Ya parece bastante lleno.")');assert.equal(els.toast.dataset.kind,'ordinary');advance(1999);assert.equal(els.toast.hidden,false);advance(1);assert.equal(els.toast.classList.contains('visible'),false);advance(180);assert.equal(els.toast.hidden,true);
 run('showPanel("training")');const practice=els['panel-content'].querySelectorAll('button').find(b=>b.dataset.key==='iq');practice.fire('click');assert.equal(els.panel.open,false);assert.equal(els['training-game'].open,true);advance(40000);await flush();assert.equal(els.hambre.classList.contains('meter-changed'),true);assert.equal(els.energia.classList.contains('meter-changed'),true);assert.equal(els.toast.dataset.kind,'ordinary');
 run('showPanel("settings")');const force=els['panel-content'].querySelectorAll('button').filter(b=>b.dataset.key?.startsWith('force-'));assert.equal(force.length,1);force[0].fire('click');assert.equal(els.panel.open,false);assert.equal(run('state.pokemonId'),'pikachu');assert.equal(els.toast.dataset.kind,'event');assert.equal(els.sprite.classList.contains('evolving'),true);
 run('showPanel("settings")');assert.equal(els['panel-content'].querySelectorAll('button').filter(b=>b.dataset.key?.startsWith('force-')).length,2);run('closePanel();forceEvolution("raichu");showPanel("settings")');assert.equal(els['panel-content'].querySelectorAll('button').filter(b=>b.dataset.key?.startsWith('force-')).length,0);
 run('closePanel();state.pokemonId="marill";render()');await flush();assert.equal(els.sprite.dataset.visual,'asset');assert.equal(els.sprite.children[0].width,run('PokemonRenderer.geometry("marill").width'));assert.equal(els.sprite.children[0].height,run('PokemonRenderer.geometry("marill").height'));assert.ok(els.sprite.children[0].context.draws.length>0);assert.equal(els.sprite.children[0].context.imageSmoothingEnabled,false);
 const imageCount=t.images.length;run('render();render();render()');await flush();assert.equal(t.images.length,imageCount);
 doc.hidden=true;doc.events.visibilitychange();const draws=els.sprite.children[0].context.draws.length;advance(1000);assert.equal(els.sprite.children[0].context.draws.length,draws);doc.hidden=false;doc.events.visibilitychange();await flush();const resumedDraws=els.sprite.children[0].context.draws.length;advance(500);assert.ok(els.sprite.children[0].context.draws.length>resumedDraws);
 run('state.pokemonId="pichu";render()');await flush();assert.equal(els.sprite.dataset.visual,'asset');
 const rows=run('Object.keys(evolutionConfig).map(id=>[id,PokemonRenderer.definition(id).type])');assert.equal(rows.filter(([,type])=>type==='sheet').length,44);assert.equal(rows.filter(([,type])=>type==='matrix').length,0);
 for(const [id,type] of rows){run(`state.pokemonId='${id}';render()`);await flush();assert.equal(els.sprite.dataset.visual,type==='matrix'?'placeholder':'asset',id);assert.equal(els.sprite.textContent,'');if(type==='sheet'){assert.ok(els.sprite.children[0].context.draws.length>0,id);assert.equal(els.sprite.children[0].width,run(`PokemonRenderer.geometry("${id}").width`));assert.equal(els.sprite.children[0].height,run(`PokemonRenderer.geometry("${id}").height`));}}
 const old=await setup({initialSave:{version:10}});assert.equal(old.run('state.version'),12);assert.equal(old.run('state.phase'),'egg');assert.ok(old.run('storageWarning.includes("D inicia")'));
 const checkpoint=JSON.parse(run('JSON.stringify(state)'));const restored=await setup({initialSave:checkpoint});assert.equal(restored.run('state.social.active.id'),checkpoint.social.active.id);
 const bad=await setup({missing:true});bad.run('state.incubationRemaining=0;hatch(()=>0);finishBirthScene();setNickname("");state.pokemonId="marill";render()');await bad.flush();assert.equal(bad.els.sprite.dataset.visual,'placeholder');assert.equal(bad.els.sprite.children[0].tagName,'canvas');
 // Late image completions cannot replace an egg after reset.
 run('state.pokemonId="marill";render();resetGame()');await flush();assert.equal(run('state.phase'),'egg');assert.equal(els.toast.hidden,true);
 const reduced=await setup({reduced:true});reduced.run('state.incubationRemaining=0;hatch(()=>0);finishBirthScene();setNickname("");state.pokemonId="marill";render()');await reduced.flush();const reducedDraws=reduced.els.sprite.children[0].context.draws.length;reduced.advance(1000);assert.equal(reduced.els.sprite.children[0].context.draws.length,reducedDraws);
 const html=fs.readFileSync('index.html','utf8');assert.ok(!html.includes('current().emoji'));assert.ok(!html.includes('?.emoji'));assert.ok(html.includes('image-rendering:pixelated'));assert.ok(html.includes('id="message-strip"')); assert.ok(html.includes('max-height:36px'));
 console.log('PASS C.1 UI/renderer: silent egg with visual reaction, transient feedback, immediate training flashes, force controls, 44 species sheets, no missing mappings, load failure/reduced state lifecycle, integer scaling and no Pokémon emoji fallback.');
})().catch(e=>{console.error(e);process.exitCode=1});
