const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8'),script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
async function setup({missing=false,reduced=false,initialSave=null,initialDisplayMode=null,initialShells=null}={}){
 let now=1000000,next=0,doc;const timeouts=new Map(),intervals=new Map(),storage=new Map(),images=[];
 class E{constructor(tag='div'){this.tagName=tag;this.children=[];this.dataset={};this.events={};this.textContent='';this.value='';this.style={setProperty(k,v){this[k]=v}};this.classList={set:new Set(),contains(x){return this.set.has(x)},add(...a){a.forEach(x=>this.set.add(x))},remove(...a){a.forEach(x=>this.set.delete(x))},toggle(x,on){on?this.set.add(x):this.set.delete(x)}};this.hidden=false;this.open=false;}
 getContext(){return this.context??=( {draws:[],fillRect(){},strokeRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},clearRect(){},save(){},restore(){},translate(){},scale(){},drawImage(...args){this.draws.push(args)}} )}toDataURL(){return 'data:image/png;base64,AA=='}play(){return Promise.resolve()}select(){}setAttribute(k,v){this[k]=v}addEventListener(k,f){(this.events[k]??=[]).push(f)}fire(k){for(const f of this.events[k]||[])f({target:this,preventDefault(){},stopPropagation(){}})}append(...a){this.children.push(...a)}replaceChildren(...a){this.children=a;this.textContent=''}get firstChild(){return this.children[0]}querySelectorAll(s){return this.children.flatMap(e=>[...(e.tagName==='button'?[e]:[]),...e.querySelectorAll(s)])}focus(){doc.activeElement=this}showModal(){this.open=true}close(){this.open=false;this.fire('close')}}
 const els={};for(const m of html.matchAll(/<([a-z]+)[^>]*\bid="([^"]+)"[^>]*>/g)){els[m[2]]=new E(m[1]);els[m[2]].hidden=/\bhidden\b/.test(m[0]);}
 const actions=[...html.matchAll(/<button[^>]*data-action="([^"]+)"/g)].map(m=>{const e=new E('button');e.dataset.action=m[1];return e});
 const panels=['inventory','training','oak','settings'].map(p=>{const e=new E('button');e.dataset.panel=p;return e});
 doc={activeElement:null,hidden:false,events:{},getElementById:id=>els[id]||Object.values(els).flatMap(root=>{const walk=e=>[e,...e.children.flatMap(walk)];return walk(root)}).find(e=>e.id===id)||null,createElement:t=>new E(t),querySelectorAll:s=>s==='[data-action]'?actions:panels,querySelector:s=>actions.find(b=>s.includes(`"${b.dataset.action}"`)),addEventListener(k,f){this.events[k]=f}};
 const motion={matches:reduced,addEventListener(k,f){this.changed=f}};
 const win={events:{},matchMedia:()=>motion,addEventListener(k,f){this.events[k]=f}};
 class Image extends E{constructor(){super('img');this.naturalWidth=512;this.naturalHeight=512;images.push(this)}set src(s){this.url=s;if(s.startsWith('assets/sprites/')||s.startsWith('assets/pmd/')){if(!fs.existsSync(s)){Promise.resolve().then(()=>this.onerror?.());return;}const png=fs.readFileSync(s);this.naturalWidth=png.readUInt32BE(16);this.naturalHeight=png.readUInt32BE(20);}Promise.resolve().then(()=>missing?this.onerror?.():this.onload?.())}}
 if(initialShells)storage.set('hatch.mon.shells',JSON.stringify(initialShells));
 if(initialDisplayMode)storage.set('hatch.mon.displayMode',initialDisplayMode);
 if(initialSave)storage.set('hatch.mon.v3',JSON.stringify(initialSave));
 const ctx=vm.createContext({TextEncoder,TextDecoder,btoa,atob,crypto:require('node:crypto').webcrypto,Image,document:doc,window:win,performance:{now:()=>now},Date:class extends Date{static now(){return now}},Math:Object.assign(Object.create(Math),{random:()=>.5}),setTimeout(fn,delay){timeouts.set(++next,{fn,at:now+delay});return next},clearTimeout:id=>timeouts.delete(id),setInterval(fn){intervals.set(++next,fn);return next},clearInterval:id=>intervals.delete(id),localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}});
 const run=s=>vm.runInContext(s,ctx),flush=async()=>{for(let i=0;i<12;i++)await Promise.resolve()};
 const advance=ms=>{const end=now+ms;let n=0;while(true){const d=[...timeouts].filter(([,t])=>t.at<=end+1e-7).sort((a,b)=>a[1].at-b[1].at)[0];if(!d)break;if(n++>20000)throw Error('timer loop');now=d[1].at;timeouts.delete(d[0]);d[1].fn()}now=end;};
 run(fs.readFileSync('evolutionTable.js','utf8'));run(fs.readFileSync('hatchmonData_v2.js','utf8'));run(fs.readFileSync('pokemonDataAdapter.js','utf8'));run(fs.readFileSync('vitalSimulation.js','utf8'));for(const f of ['relationship.js','pokedex.js','shiny.js','assets/skins/themes.js','shellSkins.js','styleTracing.js','trainingActivities.js','assets/pmd/manifest.js','assets/pmd/listMetrics.js','pmdRenderer.js'])run(fs.readFileSync(f,'utf8'));run(fs.readFileSync('pokemonRenderer.js','utf8'));run(fs.readFileSync('socialEngine.js','utf8'));run(fs.readFileSync('vendor/qrcode.js','utf8'));run(script);await flush();
 return {run,flush,advance,els,timeouts,intervals,images,doc,win,motion,storage};
}

module.exports={setup};
