"""Perceptual list metrics from the first PMD Idle frame, without species scale overrides."""
from pathlib import Path
import json
from PIL import Image
root=Path(__file__).resolve().parents[1];metrics={}
for path in sorted((root/'assets/pmd').glob('*/metadata.json')):
 data=json.loads(path.read_text());idle=data['sprites'].get('Idle')
 if not idle:continue
 alpha=Image.open(root/idle['src']).convert('RGBA').crop((0,0,idle['width'],idle['height'])).getchannel('A');box=alpha.getbbox()
 metrics[data['pokemonId']]={'opaqueArea':sum(v/255 for v in alpha.getdata()),'width':box[2]-box[0],'height':box[3]-box[1]}
(root/'assets/pmd/listMetrics.js').write_text('/* Generated by tools/generateListMetrics.py. */\nconst PMD_LIST_METRICS='+json.dumps(metrics,separators=(',',':'))+';\n')
print('List metrics:',len(metrics))
