"""Deterministic shell themes sampled from local PMD Idle sprites."""
from pathlib import Path
from collections import Counter
import json
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
def mix(color,target,amount):return '#'+''.join(f'{round(c*(1-amount)+target*amount):02x}' for c in color)
themes={}
overrides=json.loads((ROOT/'assets/skins/motifOverrides.json').read_text())
for file in sorted((ROOT/'assets/pmd').glob('*/metadata.json')):
 data=json.loads(file.read_text());idle=data['sprites'].get('Idle')
 if not idle:continue
 image=Image.open(ROOT/idle['src']).convert('RGBA').crop((0,0,idle['width'],idle['height']))
 colors=Counter((r,g,b) for r,g,b,a in image.getdata() if a>200 and max(r,g,b)-min(r,g,b)>25)
 if not colors:colors=Counter((r,g,b) for r,g,b,a in image.getdata() if a>200)
 color=colors.most_common(1)[0][0]
 themes[data['pokemonId']]={'name':data['name'],'shellBase':mix(color,255,.48),'shellDark':mix(color,0,.60),'shellLight':mix(color,255,.80),'accent':mix(color,0,.12),'bezel':mix(color,0,.65),'button':mix(color,255,.87),'patternType':'band','patternIntensity':.09}
for pid,override in overrides.items():
 if pid in themes:themes[pid].update(override)
out=ROOT/'assets/skins';out.mkdir(exist_ok=True)
(out/'themes.js').write_text('/* Generated by tools/generateShellThemes.py from PMD Idle pixels. */\nconst SHELL_THEMES='+json.dumps(themes,ensure_ascii=False,separators=(',',':'))+';\n')
print(len(themes),'shell themes generated')
